### ISSUE TITLE
Unique validator

### ISSUE THREAD

**Issue by tsukasa-mixer** [MindyPHP/Mindy_Form#25]
Если в модели присутвует Unique validator в форме будет вызыватся ошибка при попытке валидации.

**Comment by max107** [comment]
Логично.

**Comment by qantus** [comment]
Почему логично?

**Comment by max107** [comment]
Недостаточно информации по задаче. Судя по описанному в задаче поведение выглядит адекватным.

**Comment by qantus** [comment]
Валидаторы наследуются все, в том числе и Uniqiue, внутри него обращение к $this->getModel(). У формы модели нет, поэтому вызывается ошибка.

**Comment by qantus** [comment]
Это, как я понял.

**Comment by tsukasa-mixer** [comment]
Если валидатор от модели наследуется в форму, то в форме должен быть некий обработчик данного события иначе непонятно зачем он там такой.

**Comment by max107** [comment]
> У формы модели нет
У `ModelForm` есть метод `getModel()`

> некий обработчик данного события
Какого события?

**Comment by tsukasa-mixer** [comment]
unvique валидации

**Comment by max107** [comment]
@tsukasa-mixer ты можешь полностью описать проблему?
